
# cargo-vet config file
default-criteria = "safe-to-run"

[policy.adhd-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.bindgen-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Only safe-to-run is required, as this is a host tool."

[policy.chromeos-dbus-bindings]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.chunnel]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.crash_rust_panic]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.crdyboot]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.cronista]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.croscomp]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.crosh]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.crostini_client]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.crosvm]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.cxxbridge-cmd-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Only safe-to-run is required, as this is a host tool."

[policy.dbus-codegen-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Only safe-to-run is required, as this is a host tool."

[policy.deqp-runner]
audit-as-crates-io = false
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.deqp-runner-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.dlib]
audit-as-crates-io = false
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.dlib-test]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.factory_installer]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.featured]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.flashrom_tester-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Only safe-to-run is required, as this is a host tool."

[policy.floss]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.hiberman]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.hps-firmware]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.hwsec-utils]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.ippusb_bridge]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.lego-controller]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.libchromeos]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.libflashrom-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.libflashrom-sys-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.libsirenia]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.manatee-client]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.manatee-runtime]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.memd]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.minijail]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.minijail-sys]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.os_install_service]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.p9s]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.pinned_crates]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.prjoxide-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Only safe-to-run is required, as this is a host tool."

[policy.pyprjoxide-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Only safe-to-run is required, as this is a host tool."

[policy.resourced]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.riscv-rt-macros-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.rustc-demangle-capi-deps]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.sirenia]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.sirenia-rpc-macros]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.system_api]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.system_api_chunnel]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.uwb_core_hal]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.uwbd]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.vboot_reference-sys]
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.wayland-commons]
audit-as-crates-io = false
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.wayland-scanner]
audit-as-crates-io = false
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.wayland-server]
audit-as-crates-io = false
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

[policy.wayland-sys]
audit-as-crates-io = false
criteria = ["safe-to-run", "crypto-safe"]
dev-criteria = ["safe-to-run", "crypto-safe"]
notes = "Using relaxed target criteria to help with migration."

