crate_name = "memchr"
version = "2.4.1"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
# Some simple unsafe uses (e.g., calling libc::memchr), others involve things
# like type punning and doing SIMD-like operations with `usize` (e.g., splat a
# u8 across a `usize` and `cmp` that, rather than looping across 4x u8 values)
#
# There are also just entire functions marked as `unsafe`. These use SIMD
# intrinsics directly.
has_unsafe_code = true
implements_crypto = false
