crate_name = "once_cell"
version = "1.17.0"
reviewed-by-team = "crosvm"

[common]
code_is_not_malicious = true
# provides unsafe version of API, some pointers are dereferenced & Send/Sync are
# implemented manually.
has_unsafe_code = true
build_script = false
proc_macro = false
