crate_name = "proc-macro2"
version = "1.0.49"
reviewed-by-team = "ChromeOS"

[common]
code_is_not_malicious = true
# Defines unsafe functions (from_str_unchecked), and uses `unsafe` when
# constructing a `ManuallyDrop` instance.
has_unsafe_code = true
implements_crypto = false
