# Annotations for crates required for both no_std mode and alchemy.
# For more information on annotations, see crates_universe's docs:
# https://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation
#
# Mechanically speaking, these annotations are represented as a
# `Map<CrateName, List<AnnotationsObject>>`. Each `AnnotationsObject` is fed
# directly into `crate.annotation` by `rules_rust`. `./vendor.py` turns these
# into the form bazel expects (read: JSON). They're maintained as toml so
# comments can be used, and for consistency with all of the other toml files
# here.

[[rustix]]
# Rustix has a custom build.rs which adds "-Lsrc/backend/linux_raw/arch/outline".
# (see https://github.com/bytecodealliance/rustix/blob/main/build.rs#L7)
# However, in bazel, the working directory is different.
additive_build_file_content = """
load("@@//third_party/rust_crates/bazel_files:symlink.bzl", "symlink")

config_setting(
  name = "is_release",
  values = {"compilation_mode": "opt"}
)

symlink(
    name = "static_libs",
    actual = select({
        ":is_release": "src/backend/linux_raw/arch/outline/release",
        "//conditions:default": "src/backend/linux_raw/arch/outline/debug",
    }),
)
"""
data = [":static_libs"]
rustc_flags = ["-L$(location :static_libs)"]
