# Annotations for crates specifically outside of no_std mode.
# For more information on annotations, see crates_universe's docs:
# https://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation
#
# Mechanically speaking, these annotations are represented as a
# `Map<CrateName, List<AnnotationsObject>>`. Each `AnnotationsObject` is fed
# directly into `crate.annotation` by `rules_rust`. `./vendor.py` turns these
# into the form bazel expects (read: JSON). They're maintained as toml so
# comments can be used, and for consistency with all of the other toml files
# here.

[[libusb1-sys]]
# libusb1-sys has a build script that tries to locate and arrange a link to
# libusb-1.0.
# TODO: This depends on system libraries, and won't work for boards. Need to
# wire up data dependencies properly & deal with e.g., the board root.
gen_build_script = false
rustc_flags = ["-l", "usb-1.0", "-L", "native=/usr/lib64"]
version = "*"
