[package]
name = "shadercached"
version = "0.2.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.56"
dbus = "0.9.3"
dbus-crossroads = "0.5.0"
dbus-tokio = "0.7.5"
hex = "0.4.3"
lazy_static = "1.4.0"
openssl = "0.10.41"
protobuf = "2.24.1"
regex = "1.6.0"
sys-info = "0.9.1"
tokio = { version = "1.19.2", features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
] }
