[package]
name = "crdyboot"
version = "1.0.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
ext4-view = "0.9.1"
gpt_disk_io = "0.16.2"
log = "0.4"
object = { version = "0.31.1", default-features = false, features = ["pe", "read_core", "unaligned"] }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
printf-compat = { version = "0.2", default-features = false }
sbat = { version = "0.5.0", features = ["alloc"] }
sha2 = { version = "0.10.6", default-features = false }
thiserror = { version = "2.0.0", default-features = false }
uefi = { version = "0.34", default-features = false, features = ["alloc"] }
uguid = "2.0"

[dev-dependencies]
mockall = "0.12.1"
object = { version = "0.31.1", default-features = false, features = ["write_core"] }
regex = "1.6.0"

[build-dependencies]
bindgen = "0.69.4"
