[package]
name = "crdyboot"
version = "1.0.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
ed25519-compact = { version = "1.0.0", default-features = false }
ext4-view = "0.4.0"
log = "0.4"
object = { version = "0.31.1", default-features = false, features = ["pe", "read_core", "unaligned"] }
printf-compat = { version = "0.1", default-features = false }
sbat = { version = "0.5.0", features = ["alloc"] }
uefi = { version = "0.29", default-features = false, features = ["alloc"] }
uguid = "2.0"

[dev-dependencies]
mockall = "0.12.1"
object = { version = "0.31.1", default-features = false, features = ["write_core"] }
regex = "1.6.0"

[build-dependencies]
bindgen = "0.69.4"
