[package]
name = "uwbd"
version = "0.0.1"
authors = ["The Chromium OS Authors"]
edition = "2018"

[build-dependencies]
protoc-rust = "2.24.1"
# TODO(phuleh) - Remove pdl-compiler 0.1.1 once uwbd is updated
pdlc-01 = { package = "pdl-compiler", version = "0.1.1" }
pdlc-02 = { package = "pdl-compiler", version = "0.2.2" }

[dependencies]
dbus = "0.9.3"
dbus-crossroads = "0.5.0"
futures = "0.3.13"
log = "0.4.14"
protobuf = "2.24.1"
syslog = "6.0.1"
